apiVersion: v1
kind: Secret
metadata:
  name: agentic-ai-secrets
  namespace: homemind
stringData:
  GOOGLE_AI_API_KEY: ""
  OPENAI_API_KEY: ""
  PINECONE_API_KEY: ""
  NEO4J_URI: ""
  NEO4J_USERNAME: ""
  NEO4J_PASSWORD: ""
