apiVersion: v1
kind: Service
metadata:
  name: homemind-backend
  labels:
    app: homemind-backend
    app.kubernetes.io/part-of: homemind
  namespace: homemind
spec:
  selector:
    app: homemind-backend
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: ClusterIP
