apiVersion: v1
kind: ConfigMap
metadata:
  name: homemind-shared-config
  labels:
    app.kubernetes.io/part-of: homemind
  namespace: homemind
data:
  NODE_ENV: production
  PORT: "3001"
  FRONTEND_PORT: "3000"
