apiVersion: v1
kind: Service
metadata:
  name: homemind-frontend
  labels:
    app: homemind-frontend
    app.kubernetes.io/part-of: homemind
  namespace: homemind
spec:
  selector:
    app: homemind-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
