apiVersion: v1
kind: Secret
metadata:
  name: homemind-secrets
  namespace: homemind
stringData:
  mongoUri: ""
  googleAiApiKey: ""
  pineconeApiKey: ""
  pineconeIndex: "homemind-index"
  jwtSecret: ""
